### PR TITLE
.NET 6.0

### PR DESCRIPTION
**Pull request by acesnik**
Updating to use .NET 6, since end of support for .NET 5 is May 8, 2022
https://github.com/smith-chem-wisc/mzLib/issues/614

### CODE REVIEW

**Comment by trishorts** [comment]
i'll checkout the code to see if i can handle the webclient thing. have to look at thermofilereader and see if and what needs to be done there.

this kind of change terrifies me....

**Comment by acesnik** [comment]
From what I understand, net5.0 -> net6.0 is a more minor change than netcore3.0 -> net5.0, so this should hopefully be smoother.

**Comment by acesnik** [comment]
Thanks for checking it out @trishorts. :)

**Comment by trishorts** [comment]
im getting some unit test failures. i updated my computer to net6.0 (maybe i shouldn't have but I did).

**Comment by trishorts** [comment]
drafted an example change in [mzLib/UsefulProteomicsDatabases/Loaders.cs](https://github.com/smith-chem-wisc/mzLib/pull/615/files#diff-95c9dbae63c2789923190a00aee77bb89b41e5361e4bbda05686e2753f7e6439) changing webclient to httpclient. see if that is okay as a prototype for other uses of webclient

**Comment by acesnik** [comment]
What was the motivation of changing over to httpclient? Was webclient crashing?

**Comment by acesnik** [comment]
Oh, I see what you're seeing now.

**Comment by acesnik** [comment]
Looks like there was a change in printing xml structures: https://stackoverflow.com/questions/69441535/net-6-xmlserializer-pretty-print

**Comment by acesnik** [comment]
Looks like there was a change in printing xml structures: https://stackoverflow.com/questions/69441535/net-6-xmlserializer-pretty-print

**Comment by acesnik** [comment]
I wrapped this one up. Should be ready to go. I had to make some changes to writing mzMLs (issue writing whitespace) and HTTPClient (issue downloading gzipped files).

**Review by trishorts — APPROVED** [review]
i did not get async download to work in my hands but maybe you had better luck???

**Review by trishorts — APPROVED** [review]

**Comment by acesnik** [comment]
Here's the MetaMorpheus PR, which still has a minor issue with spectral library generation to consider along with this PR :) https://github.com/smith-chem-wisc/MetaMorpheus/pull/2130

**Comment by acesnik** [comment]
Perhaps the spectral library stuff is all within MetaMorpheus, though, and maybe it should be handled there.

**Pull request merged**
