### PR TITLE
LoadPsiMod changed to close FileStream after reading in data

### PR DESCRIPTION
**Pull request by Alexander-Sol**
TestLoading test in TestDatabaseLoaders.cs wasn't passing on my build. The FileStream to the PsiMod file was left open when LoadPsiMod was called. This prevented the deletion of the PsiMod file.

I changed LoadPsiMod to close the FileStream before returning the data. The test now passes.

### CODE REVIEW

**Comment by kyp4** [comment]
I am able to pass the FilesLoading() test both with and without this change (not sure why), but did need to update the number of PSMs coming from Unimod: Assert.AreEqual(2723, unimodMods.Count);

**Review by kyp4 — CHANGES_REQUESTED** [review]
I am able to pass the FilesLoading() test both with and without this change (not sure why), but did need to update the number of PSMs coming from Unimod: Assert.AreEqual(2723, unimodMods.Count);

**Comment by trishorts** [comment]
number changes frequently, so this number needs updating when that happens. we've talked about adapting the unit test before but haven't yet. maybe there is another way to compute the number or do the check.

**Comment by Alexander-Sol** [comment]
Currently we're just checking that the # of PSMs is greater than 2700:  Assert.Greater(unimodsMods.Count, 2700)

**Comment by trishorts** [comment]
# of mods not number of psms but i get your point.

**Pull request closed without merging**
