### PR TITLE
32bit dynamic mzml fix

### PR DESCRIPTION
**Pull request by rmillikin**
- fixes reading 32-bit .mzML data through the dynamic connection
- fixes/tests mixed-bit scans (e.g., where the m/z values are encoded in 64 bit and the intensities are encoded in 32 bit)

### CODE REVIEW

**Comment by trishorts** [comment]
trying your pr on my file and got this
image

**Comment by trishorts** [comment]
they are in fact not equal (1.117 and 0.0816)

**Comment by trishorts** [comment]
btw, this was the converted to x64, not the original

**Comment by trishorts** [comment]
interestingly it was the static scan that was wrong...

**Comment by rmillikin** [comment]
actually it looks like the static one is correct. the RT is in seconds in the .mzML, which the static correctly converts to minutes, but the dynamic doesn't

**Comment by rmillikin** [comment]
ok, i fixed that error too. there was another issue which at this point i'm not sure is easy to fix. if the precursor scan number is not listed in the .mzML, the static .mzML assumes it's the previous MS1 (which may or may not be correct). the dynamic reader leaves it as null

**Review by trishorts — APPROVED** [review]

**Pull request merged**
