### PR TITLE
Read one based precursor scan number from mzml

### PR DESCRIPTION
**Pull request by trishorts**
user wants to process mzMl files where precursor scans have been removed. mzLib errors when reading these files because it looks for those scans by default. Also, it renumbers all scans in order beginning with 1. 

In this PR, we maintain the default behavior but let users opt out and instead simply use the scan numbers recorded in the supplied mzml.

I have no idea what will come of this approach.

caveat emptor.

### CODE REVIEW

**Review by lonelu — APPROVED** [review]

**Comment by lonelu** [comment]
Please merge this, thank you @trishorts

**Comment by Alexander-Sol** [comment]
Couple of dependency issues that need to be fixed

image

**Comment by lonelu** [comment]
Not sure what is happening, it doesn't seem like related to this pull request.

> Couple of dependency issues that need to be fixed
> 
> image

**Review by acesnik — DISMISSED** [review]

**Review by lonelu — APPROVED** [review]

**Comment by trishorts** [comment]
> Couple of dependency issues that need to be fixed
> 
> image

nuget package dependencies are now resolved.

**Review by Alexander-Sol — APPROVED** [review]

**Review by acesnik — APPROVED** [review]

**Review by lonelu — APPROVED** [review]

**Pull request merged**
