### PR TITLE
Restructure base directory & add GitHub Actions builds/releases

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by acesnik** [comment]
This PR simplifies the landing page for mzLib. It will need some adjustment to AppVeyor before merging if we decide this is something we'd like to do.

Before:
image

After:
image

**Comment by trishorts** [comment]
do you know how to adjust appveyor?
does this update change links to objects in programs like MM that use mzlib?

**Comment by acesnik** [comment]
This would aim to move mzLib over to using github actions instead of appveyor, so that the whole pipeline could be housed in github rather than two places. (Easier maintenance)

I've drafted the github action files in this PR, as well.

The links won't change, since the nuspec file is packaged the same way, and the nupkg would be released into GitHub releases.

**Comment by acesnik** [comment]
The builds will also be reported and kept here https://github.com/smith-chem-wisc/mzLib/actions
The secrets for pushing releases are also kept secure on GitHub, which makes them easier to find

**Comment by acesnik** [comment]
I'll note I haven't figured out codecov in GitHub Actions just yet, but I'd be happy to put a little more work in to figure that out if this continuous integration change is something the group is interested in. :)

**Comment by acesnik** [comment]
Codecov is now working under Github Actions in this PR. Should obviate the need for AppVeyor.

image

**Comment by acesnik** [comment]
I think the appveyor build failure is signaling to Codecov not to post this, but here's what it'll look like with the codecov report:
image

**Comment by trishorts** [comment]
I think this PR makes good sense. The one concern I have, which may be totally unfounded, is how programs that use mzlib (like MM) will find existing classes. Do their paths change?

**Comment by acesnik** [comment]
Their paths do not change for other programs. You can see this in the empty diff for mzlib.nuspec: https://github.com/smith-chem-wisc/mzLib/pull/577/files#diff-4678f0a7d73f29ffd80f0d7ad24ddd30beef7f96f1498431fe78723d6e4b479a. That nuspec is used to package the nupkg package that other programs use.

**Review by trishorts — DISMISSED** [review]
I'm down to try this. I never liked the verbose directory on the landing page.

**Comment by acesnik** [comment]
Updated the release branch and the settings for the repository. Should be good to go!

Also, the codecov feedback is working now with GitHub Actions!

**Comment by acesnik** [comment]
Should be ready to go @rmmiller22 & @trishorts!

**Review by trishorts — APPROVED** [review]

**Pull request merged**
