### PR TITLE
digest protein filter glycopeptide

### PR DESCRIPTION
**Pull request by lonelu**
glycopeptide analysis usually only focuses on the peptide with glycan modification motif. This pull request is to only keep glycopeptide after digestion for creating a focused database.

### CODE REVIEW

**Comment by acesnik** [comment]
Can you squash merge this to clean up the git history? https://stackoverflow.com/a/5309051

**Comment by acesnik** [comment]
I don't get why your build is trying to place TestFlashLFQ in a different place than the last build of the master branch 3 mo ago.

Here is that build 3 mo ago:
image

Here is yours:
image

Did something change in the AppVeyor settings in the meantime?

**Comment by acesnik** [comment]
GitHub Actions is more stable than AppVeyor because the settings are imbedded in the repository by default. I think we should consider switching mzLib (and maybe MM too) over soon. https://github.com/smith-chem-wisc/MetaMorpheus/issues/2088

**Comment by acesnik** [comment]
Nothing changed in the settings, per se. The build tool on AppVeyor changed, though. I switched it over to "Previous Visual Studio 2019," and that seems to be working.

**Comment by acesnik** [comment]
Nothing changed in the settings, per se. The build tool on AppVeyor changed, though. I switched it over to "Previous Visual Studio 2019," and that seems to be working.

**Comment by acesnik** [comment]
It's past that point now, but there's a test failure, it looks like.
image

**Review by acesnik — CHANGES_REQUESTED** [review]
* Squash-merge to clean up git history if possible
* Fix failing test

**Comment by lonelu** [comment]
Thanks, Anthony for help reviewing this. I didn't have a clue what's wrong with it.  
I don't know how to Squash-merge in this branch, so I created a new branch in a new pull request.

**Comment by acesnik** [comment]
Sounds good! Will close this one.

**Pull request closed without merging**
