### PR TITLE
Fix indel decoy error

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by rmillikin** [comment]
some issue building FlashLFQ?

**Comment by acesnik** [comment]
Yeah, I don't get it. I tried changing the AppVeyor build environment to all of the VS 2017 versions. That didn't help.

**Comment by acesnik** [comment]
The master branch is broken now, too. https://ci.appveyor.com/project/smith-chem-wisc/mzlib

**Comment by rmillikin** [comment]
```
C:\projects\mzlib\ManagedThermoHelperLayer\ClassLibrary1.vcxproj : warning NU1503: Skipping restore for project 'C:\projects\mzlib\ManagedThermoHelperLayer\ClassLibrary1.vcxproj'. The project file may be invalid or missing targets required for restore. [C:\projects\mzlib\mzLib.sln]
C:\projects\mzlib\UnmanagedThermoHelperLayer\Win32Project8.vcxproj : warning NU1503: Skipping restore for project 'C:\projects\mzlib\UnmanagedThermoHelperLayer\Win32Project8.vcxproj'. The project file may be invalid or missing targets required for restore. [C:\projects\mzlib\mzLib.sln]
```
?

**Comment by rmillikin** [comment]
this is from an old build...

```
[00:02:11]   Win32Project8.vcxproj -> C:\projects\mzlib\x64\Release\UnmanagedThermoHelperLayer.dll
[00:02:15]   ClassLibrary1.vcxproj -> C:\projects\mzlib\x64\Release\ManagedThermoHelperLayer.dll
```

seems like some issue building thermo stuff?

**Comment by acesnik** [comment]
Yeah, that's weird. Are there any nuget packages or something that have to be restored in the C++ packages? Is it something to do with the mzLib.targets file?

**Comment by acesnik** [comment]
There's also this `Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1332,5): error MSB3073: The command "xcopy /y /d  "C:\projects\mzlib\x64\Release\*.dll" "C:\projects\mzlib\Thermo\bin\x64\Release\"" exited with code 4. [C:\projects\mzlib\Thermo\Thermo.csproj]`

**Comment by acesnik** [comment]
This is ready to go for tomorrow.

**Pull request merged**
