### PR TITLE
Add missing target framework moniker (TFM) piece

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by trishorts** [comment]
what does this pr do?

**Comment by trishorts** [comment]
is windows 7 some sort of min value?

**Comment by acesnik** [comment]
Yes, 7.0 is the default now. I remember seeing this a long time ago, so I wanted to jump in and make this because it could be tough to figure out these weird errors with nuspec.

It's building now:
image

**Comment by acesnik** [comment]
Don't ask me why 7.0 is the default, because I have no idea. 😅

**Comment by acesnik** [comment]
The PR is aimed at getting mzLib to build with an updated version of nuspec that's now on AppVeyor.

**Review by trishorts — APPROVED** [review]

**Pull request merged**
